### ISSUE TITLE
Solang compatibility

### ISSUE THREAD

**Issue by jb33k** [multiversx/mx-chain-vm-go#171]
Has anybody tested whether Hyperledger's Solang https://github.com/hyperledger-labs/solang produces wasm that Arwen can run? Elrond looks fantastic, but incompatibility with Solidity is a bummer.

**Comment by jb33k** [comment]
3 days and noone bothers to answer. This project is off to a great start.

**Comment by sasurobert** [comment]
Hi @jb33k ! 

Sorry for not responding earlier. Earlier this year we tried SOLL compiler, but it had a lot of flaws and it did not support structures, interfaces, calling another smart contract and much more. 
We will go and look into Solang as well and see if it fits the purpose. The Ethereum EI is implemented and it is in the Arwen VM, however currently we recommend to rewrite the contract using our rust framework. We added a lot of improvements on how contracts should be written and tested. There is default SafeMath in Elrond EI, rust framework uses that directly, no need to bother with under/overflow exception.
Bringing a smart contract from Ethereum, rewriting it in RUST takes roughly a day per 500 lines of code.

Solang looks great for now, but we will wait a little bit more to have some of the missing features implemented and to have it stable. We will be among the first ones to integrate in our toolchain when it is ready.

**Comment by jb33k** [comment]
Thanks for the reply. I agree 100% that all smart contracts should be rewritten with Rust, but unfortunately it's highly unlikely that will happen anytime soon. Soland does seem to have pretty much everything you listed as missing from SOLL. Only thing that might cause problems, depending how you've designed your contracts, is the missing `super`.
